//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocenteExperienciaEducativa
    {
        public int DocenteID { get; set; }
        public int ExperienciaEducativaID { get; set; }
        public string Periodo { get; set; }
    
        public virtual Docente Docente { get; set; }
        public virtual ExperienciaEducativa ExperienciaEducativa { get; set; }
    }
}
