//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienciaEducativa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExperienciaEducativa()
        {
            this.DocenteExperienciaEducativa = new HashSet<DocenteExperienciaEducativa>();
        }
    
        public int ExperienciaEducativaID { get; set; }
        public int ProgramaEducativoID { get; set; }
        public string Bloque { get; set; }
        public string Seccion { get; set; }
        public Nullable<int> CreditosEe { get; set; }
        public Nullable<int> HSM { get; set; }
        public string NombreEE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocenteExperienciaEducativa> DocenteExperienciaEducativa { get; set; }
        public virtual ProgramaEducativo ProgramaEducativo { get; set; }
    }
}
